const catchError = require('../utils/catchError');
const Episode = require('../models/Episode');
const Character = require('../models/Character');

const getAll = catchError(async(req, res) => {
    const results = await Episode.findAll({include: [Character]});
    return res.json(results);
});

const create = catchError(async(req, res) => {
    const result = await Episode.create(req.body);
    return res.status(201).json(result);
});

const getOne = catchError(async(req, res) => {
    const { id } = req.params;
    const result = await Episode.findByPk(id);
    if(!result) return res.sendStatus(404);
    return res.json(result);
});

const remove = catchError(async(req, res) => {
    const { id } = req.params;
    await Episode.destroy({ where: {id} });
    return res.sendStatus(204);
});

const update = catchError(async(req, res) => {
    const { id } = req.params;
    const result = await Episode.update(
        req.body,
        { where: {id}, returning: true }
    );
    if(result[0] === 0) return res.sendStatus(404);
    return res.json(result[1][0]);
});

module.exports = {
    getAll,
    create,
    getOne,
    remove,
    update
}